### ISSUE TITLE
Git failure

### ISSUE THREAD

**Issue by antarr** [vk26/action-fasterer#6]
I'm getting the failure below when running my job.

**error**
```
reviewdog: GitHubPullRequest needs 'git' command: failed to run 'git rev-parse --show-prefix': exit status 128
/usr/local/bundle/gems/fasterer-0.10.1/lib/fasterer/file_traverser.rb:86:in `write': Broken pipe @ io_write - <STDOUT> (Errno::EPIPE)
```

quality.yml
```yaml
name: "Quality"
on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
  pull-requests: write
concurrency:
  group: quality-${{ github.ref }}
  cancel-in-progress: true
env:
  SIMPLE_COV_REVIEW: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        run: echo 2.7.7 > .ruby-version
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      # - name: Install Extra Gems
      #   run: gem install simplecov-json simplecov-review --no-document
      # - name: Fetch main for comparison
      #   run: git fetch origin main:refs/remotes/origin/main
      - name: fasterer
        uses: vk26/action-fasterer@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check
      - name: Brakeman via Reviewdog
        uses: reviewdog/action-brakeman@v2
        with:
          brakeman_version: 5.4.1
          reporter: github-pr-review # Default is github-pr-check
      - name: Rubocop via Reviewdog
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile rubocop-performance:gemfile rubocop-faker:gemfile
          reporter: github-pr-review # Default is github-pr-check
```
